require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude: 
    - db/**/*
    - config/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - vendor/**/*
    - spec/**/*
    - test/**/*
    - node_modules/**/*
Style/Documentation:
  Enabled: false    